# Introdução {#intro}

## Histórico e evolução

A partir da década de 1990, houve uma mudança significativa na forma de mensuração e gestão de riscos no segmento financeiro. Em particular, as ferramentas de gestão de riscos começaram a incorporar modelagem financeira mais complexa, explorando técnicas quantitativas, notadamente das áreas de probabilidade e estatística.

Além das exigências regulatórias que passaram a estabelecer regras e diretrizes que necessitavam de modelagem mais rigorosas do ponto de vista quantitativo, um marco importante nessa nova abordagem de gestão de riscos foi a introdução do  RiskMetrics Technical Document, pelo banco americano J.P. Morgan, em 1996. Esse documento, também chamado de RiskMetrics Classic, foi amplamento disseminado no mercado financeiro e tornou-se um benchmark para modelagem em gestão de riscos, com foco em risco de mercado.

Destaca-se, portanto, que embora os bancos estejam expostos a diversos tipos de riscos, a origem de gestão de riscos com uma abordagem quantitativa mais moderna tinha como foco o risco de mercado. 

O risco de mercado pode ser definido como a "possibilidade de ocorrência de perdas resultantes da flutuação nos valores de mercado de instrumentos detidos pela instituição". 

Assim, se uma instituição possui uma carteira de ações, o risco de mercado está associado à possibilidade de perda em função da desvalorização do valor de mercado do preço das ações, por exemplo. 
This material is under constant development and will be used to show fundamental concepts of data science.

## Regulamentação Bancária

Reference a figure by its code chunk label with the `fig:` prefix, e.g.,  Similarly, you can reference tables generated from `knitr::kable()`, e.g., see Table \@ref(tab:nice-tab).

You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015].

## Tipos de Risco

## Risco de Mercado